name: continuous integration

on:
  pull_request:
    branches:
      - develop
      - master

jobs:

  tests-unit:
    runs-on: ubuntu-latest
    container:
      image: nrel/openstudio:3.8.0
    steps:
      - uses: actions/checkout@v4
      - run: openstudio classic measure --run_tests measures