name: measures_systems

on: [workflow_call, workflow_dispatch]

env:
  SYSTEMS: main

jobs:
  update:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: sparse checkout NREL/SystemsAnalysisReports
        uses: actions/checkout@v4
        with:
          repository: NREL/SystemsAnalysisReports
          ref: ${{ env.SYSTEMS }}
          path: systems
          sparse-checkout: measure/systems_analysis_report_generator
          
      - name: copy files from NREL/SystemsAnalysisReports
        shell: bash
        run: |
          cp -r systems/measure/systems_analysis_report_generator/* measures/systems_analysis_report_generator/
          ls measures/systems_analysis_report_generator
 
      - name: upload files
        uses: actions/upload-artifact@v3
        with:
          name: measures
          path: measures

  pull-request:
    needs: update
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v3
      
      - name: list
        run: |
          ls measures/   

      - name: pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: update measures systems
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: '[action] update measures systems'
          branch: action/update-measures-systems
          base: main 
