name: measures_gbxml

on: [workflow_call, workflow_dispatch]

env:
  GBXML: main

jobs:
  update:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: sparse checkout NREL/openstudio-gbxml-measures
        uses: actions/checkout@v4
        with:
          repository: NREL/openstudio-gbxml-measures
          ref: ${{ env.GBXML }}
          path: gbxml
          sparse-checkout: |
            measures/import_gbxml
            measures/advanced_import_gbxml
            measures/gbxml_hvac_import
            measures/gbxml_postprocess

      - name: copy files from NREL/openstudio-gbxml-measures
        shell: bash
        run: |
          cp -r gbxml/measures/import_gbxml/* measures/import_gbxml/
          cp -r gbxml/measures/advanced_import_gbxml/* measures/advanced_import_gbxml/
          cp -r gbxml/measures/gbxml_hvac_import/* measures/gbxml_hvac_import/
          cp -r gbxml/measures/gbxml_postprocess/* measures/gbxml_postprocess/

      - name: upload files
        uses: actions/upload-artifact@v3
        with:
          name: measures
          path: measures

  pull-request:
    needs: update
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v3
      
      - name: list
        run: |
          ls measures/   

      - name: pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: update measures gbxml
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: '[action] update measures gbxml'
          branch: action/update-measures-gbxml
          base: main
